import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import {Heading,Text} from '@chakra-ui/react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
          <Heading fontSize={"60px"} w="40%" textAlign={"center"} m="auto" mt="100px">Welcome to the C4 evaluation for
          <Text color="teal.500"> RCT-201</Text></Heading>
          <Text color="#718096" w="70%" textAlign={"center"} m="auto" mt="40px" fontSize={"20px"}>You need to create an application similar to the one that you are looking right now. There 2 pages that needs to be created apart from the current homepage.</Text>
          <Text  w="50%" textAlign={"center"} m="auto" mt="40px" fontSize={"24px"}>One path is /people and another a dynamic route /people/[id]</Text>
         
      </main>
    </>
  )
}
